-- Script creation app Lexia
CREATE TABLE Address (  numAddress INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                        postalCode INTEGER NOT NULL,
                        postalBox VARCHAR2(255) NOT NULL,
                        locality VARCHAR2(255) NOT NULL,
                        hamlet VARCHAR2(255));

CREATE TABLE TimeSlotBase ( numTimeSlot INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            startTime DATE NOT NULL,
                            duration DATE NOT NULL,
                            dayNumber INTEGER NOT NULL);

CREATE TABLE TimeSlotPunctual ( numTimeSlot INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                startTime DATE NOT NULL,
                                duration DATE NOT NULL,
                                startDate DATE NOT NULL,
                                endDate DATE NOT NULL);

CREATE TABLE Interpreter (  numInterpreter INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            login VARCHAR2(255) NOT NULL,
                            password VARCHAR2(255) NOT NULL,
                            lastName VARCHAR2(255) NOT NULL,
                            firstName VARCHAR2(255) NOT NULL,
                            emailAddress VARCHAR2(255) NOT NULL,
                            phoneNumber VARCHAR2(255) NOT NULL,
                            weeklyWorkHours INTEGER NOT NULL,
                            FKAddress INTEGER NOT NULL,
                            CONSTRAINT FKAddressInterpreter FOREIGN KEY(FKAddress) REFERENCES Address (numAddress));

CREATE TABLE Absence (  numAbsence INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                        status VARCHAR2(255) NOT NULL,
                        reasons VARCHAR2(255),
                        privateReason NUMBER(1) NOT NULL,
                        FKTimeSlotBase INTEGER,
                        CONSTRAINT FKTimeSlotBaseAbsence FOREIGN KEY(FKTimeSlotBase) REFERENCES TimeSlotBase (numTimeSlot),
                        FKTimeSlotPunctual INTEGER,
                        CONSTRAINT FKTimeSlotPunctualAbsence FOREIGN KEY(FKTimeSlotPunctual) REFERENCES TimeSlotPunctual (numTimeSlot),
                        FKnumInterpreter INTEGER,
                        CONSTRAINT FKnumInterpreterAbsence FOREIGN KEY(FKnumInterpreter) REFERENCES Interpreter (numInterpreter));
         
CREATE TABLE Coordinator (  numCoordinator INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            isAdmin NUMBER(1) NOT NULL,
                            FKnumInterpreter INTEGER,
                            CONSTRAINT FKnumInterpreterCoordinator FOREIGN KEY(FKnumInterpreter) REFERENCES Interpreter (numInterpreter));

CREATE TABLE AcademicSkill (    numAcademicSkill INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                designation VARCHAR2(255) NOT NULL);

CREATE TABLE AcademicSkillInterpreter ( numAcademicSkill INTEGER,
                                        numInterpreter INTEGER,
                                        CONSTRAINT PKAcademicSkillInterpreter PRIMARY KEY (numAcademicSkill, numInterpreter),
                                        CONSTRAINT FKnumAcademicSkillInterpreter FOREIGN KEY(numAcademicSkill) REFERENCES AcademicSkill (numAcademicSkill),
                                        CONSTRAINT FKnumInterpreterAcademicSkillInterpreter FOREIGN KEY(numInterpreter) REFERENCES Interpreter (numInterpreter));

CREATE TABLE Establishment( numEstablishment INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            FKAddress INTEGER NOT NULL UNIQUE,
                            CONSTRAINT FKAddressEstablishment FOREIGN KEY(FKAddress) REFERENCES Address (numAddress),
                            name VARCHAR2(255),
                            phoneNumber VARCHAR2(255),
                            educationLevel VARCHAR2(255) NOT NULL);
    
CREATE TABLE Beneficiary(   numBeneficiary INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            login VARCHAR2(255) NOT NULL,
                            password VARCHAR2(255) NOT NULL,
                            firstName VARCHAR2(255) NOT NULL,
                            lastName VARCHAR2(255) NOT NULL,
                            phoneNumber VARCHAR2(255) NOT NULL,
                            emailAddress VARCHAR2(255) NOT NULL,
                            hourQuota INTEGER NOT NULL,
                            educationLevel INTEGER NOT NULL, 
                            communicationLanguage VARCHAR2(255),
                            FKnumInterpreter INTEGER,
                            CONSTRAINT FKnumInterpreterBeneficiary FOREIGN KEY (FKnumInterpreter) REFERENCES Interpreter (numInterpreter),
                            FKAddress INTEGER NOT NULL,
                            CONSTRAINT FKAddressBeneficiary FOREIGN KEY(FKAddress) REFERENCES Address (numAddress));


CREATE TABLE Appointment(   numAppointment INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            description VARCHAR2(255),
                            status VARCHAR2(255) NOT NULL,
                            local VARCHAR2(255), -- list of locals Ex : M5,M6
                            FKnumEstablishment INTEGER NOT NULL,
                            CONSTRAINT FKnumEstablishmentAppointment FOREIGN KEY (FKnumEstablishment) REFERENCES Establishment(numEstablishment),
                            FKnumBeneficiary INTEGER NOT NULL, 
                            CONSTRAINT FKnumBeneficiaryAppointment FOREIGN KEY (FKnumBeneficiary) REFERENCES Beneficiary(numBeneficiary),
                            FKTimeSlotBase INTEGER,
                            CONSTRAINT FKTimeSlotBaseAppointment FOREIGN KEY(FKTimeSlotBase) REFERENCES TimeSlotBase (numTimeSlot),
                            FKTimeSlotPunctual INTEGER,
                            CONSTRAINT FKTimeSlotPunctualAppointment FOREIGN KEY(FKTimeSlotPunctual) REFERENCES TimeSlotPunctual (numTimeSlot));

CREATE TABLE RequiredAcademicSkill (    numAppointment INTEGER,
                                        numAcademicSkill INTEGER,
                                        CONSTRAINT PKRequiredAcademicSkill PRIMARY KEY (numAppointment, numAcademicSkill),
                                        CONSTRAINT FKnumAppointmentRequiredAcademicSkill FOREIGN KEY(numAppointment) REFERENCES Appointment (numAppointment),
                                        CONSTRAINT FKnumAcademicSkillRequired FOREIGN KEY(numAcademicSkill) REFERENCES AcademicSkill (numAcademicSkill));

CREATE TABLE ProfessionalSkill( numProfessionalSkill INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 
                                designation VARCHAR2(255));

CREATE TABLE RequiredProfessionalSkill( numAppointment INTEGER,
                                        numProfessionalSkill INTEGER,
                                        PRIMARY KEY (numAppointment, numProfessionalSkill),
                                        CONSTRAINT FKnumAppointmentRequiredProfessionalSkill FOREIGN KEY (numAppointment) REFERENCES Appointment(numAppointment),
                                        CONSTRAINT FKnumProfessionalSkillRequiredProfessionalSkill FOREIGN KEY (numProfessionalSkill) REFERENCES ProfessionalSkill(numProfessionalSkill));

CREATE TABLE ProfessionalSkillInterpreter(  numProfessionalSkill INTEGER,
                                            numInterpreter INTEGER,
                                            PRIMARY KEY (numProfessionalSkill, numInterpreter),
                                            CONSTRAINT FKnumProfessionalSkillProfessionalSkillInterpreter FOREIGN KEY (numProfessionalSkill) REFERENCES ProfessionalSkill(numProfessionalSkill),
                                            CONSTRAINT FKnumInterpreterProfessionalSkillInterpreter FOREIGN KEY (numInterpreter) REFERENCES Interpreter(numInterpreter));

CREATE TABLE Referrer ( numReferer INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                        firstName VARCHAR2(255) NOT NULL,
                        lastName VARCHAR2(255) NOT NULL,
                        phoneNumber VARCHAR2(255) NOT NULL,
                        emailAddress VARCHAR2(255) NOT NULL,
                        FKEstablishment INTEGER,
                        CONSTRAINT FKEstablishmentReferrer FOREIGN KEY (FKEstablishment) REFERENCES Establishment(numEstablishment));

CREATE TABLE RDVInterpreter (   numAppointment INTEGER,
                                CONSTRAINT FKnumAppointmentRDVInterpreter FOREIGN KEY (numAppointment) REFERENCES Appointment(numAppointment),
                                numInterpreter INTEGER, 
                                CONSTRAINT FKnumInterpreterRDVInterpreter FOREIGN KEY (numInterpreter) REFERENCES Interpreter(numInterpreter),
                                CONSTRAINT PKInterpreter PRIMARY KEY (numAppointment, numInterpreter));

CREATE TABLE Work ( numReferer INTEGER, 
                    CONSTRAINT FKnumRefererWork FOREIGN KEY (numReferer) REFERENCES Referrer(numReferer),
                    numEstablishment INTEGER, 
                    CONSTRAINT FKnumEstablishementWork FOREIGN KEY (numEstablishment) REFERENCES Establishment(numEstablishment),
                    CONSTRAINT PKWork PRIMARY KEY(numReferer, numEstablishment));

-- Constraint : 

-- Email address format constraint
ALTER TABLE Referrer ADD CONSTRAINT checkEmailAddressReferrer CHECK (REGEXP_LIKE(emailAddress, '^[A-Za-z0-9._-]+@[A-Za-z0-9._-]+\.[A-Za-z]+$'));
-- Phone number constraint (just numbers)
ALTER TABLE Referrer ADD CONSTRAINT checkPhoneNumberReferrer CHECK (REGEXP_LIKE(phoneNumber, '^[0-9]+$'));

-- Working hours constraint > 0
ALTER TABLE Interpreter ADD CONSTRAINT checkWeeklyWorkHoursInterpreter CHECK (weeklyWorkHours > 0);
-- Email address format constraint
ALTER TABLE Interpreter ADD CONSTRAINT checkEmailAddressInterpreter CHECK (REGEXP_LIKE(emailAddress, '^[A-Za-z0-9._-]+@[A-Za-z0-9._-]+\.[A-Za-z]+$'));
-- Phone number constraint (just numbers)
ALTER TABLE Interpreter ADD CONSTRAINT checkPhoneNumberInterpreter CHECK (REGEXP_LIKE(phoneNumber, '^[0-9]+$'));

-- Default value of the boolean is_admin is 0
ALTER TABLE Absence MODIFY (privateReason DEFAULT 0);
-- Value of the boolean is_admin set to 0 or 1
ALTER TABLE Absence ADD CONSTRAINT checkValuePrivateReasonAbsence CHECK (privateReason = 0 or privateReason = 1);

-- The status can only be pending, accepted, rejected.
ALTER TABLE Absence ADD CONSTRAINT checkValueStatusAbsence CHECK (status like 'en attente' or status like 'accepte' or status like 'refuse');
-- The TimeSlot can only be an FKTimeSlotBase or FKTimeSlotPunctual
ALTER TABLE Absence ADD CONSTRAINT checkTimeSlotAbsence CHECK ((FKTimeSlotBase IS NULL AND FKTimeSlotPunctual IS NOT NULL) OR (FKTimeSlotBase IS NOT NULL AND FKTimeSlotPunctual IS NULL));

-- Default value of the boolean is_admin is 0
ALTER TABLE Coordinator MODIFY (isAdmin DEFAULT 0);

-- Value of the boolean is_admin set to 0 or 1
ALTER TABLE Coordinator ADD CONSTRAINT checkValueIsAdminCoordinator CHECK (isAdmin = 0 or isAdmin = 1);

-- hour_quota > 0, we cannot have a negative number of hours
ALTER TABLE Beneficiary ADD CONSTRAINT checkValueHourQuotaBeneficiary CHECK (hourQuota > 0);
-- 0 <= education_level < 5 (0 = other, 1 = kindergarten, 2 = primary, 3 = secondary, 4 = higher education)
ALTER TABLE Beneficiary ADD CONSTRAINT checkValueEducationLevelBeneficiary CHECK( REGEXP_LIKE(educationLevel,'^(0|1|2|3|4)(,(0|1|2|3|4))*$'));
-- Email address format constraint
ALTER TABLE Beneficiary ADD CONSTRAINT checkEmailAddressBeneficiary CHECK (REGEXP_LIKE(emailAddress, '^[A-Za-z0-9._-]+@[A-Za-z0-9._-]+\.[A-Za-z]+$'));
-- Phone number constraint (just numbers)
ALTER TABLE Beneficiary ADD CONSTRAINT checkPhoneNumberBeneficiary CHECK (REGEXP_LIKE(phoneNumber, '^[0-9]+$'));

-- Phone number: only numbers.
ALTER TABLE  Establishment ADD CONSTRAINT phoneNumberCheck CHECK(regexp_like(phoneNumber, '^[0-9]+$')); 
-- 0 <= education_level < 5 (0 = other, 1 = kindergarten, 2 = primary, 3 = secondary, 4 = higher education)
ALTER TABLE Establishment ADD CONSTRAINT checkValueEducationLevelEstablishment CHECK( REGEXP_LIKE(educationLevel,'^(0|1|2|3|4)(,(0|1|2|3|4))*$'));

-- The status can only be pending, accepted, rejected or cancelled.
ALTER TABLE  Appointment ADD CONSTRAINT checkStatusAppointment CHECK (lower(status) in ('en attente', 'accepte', 'refuse','annule'));
-- The TimeSlot can only be an FKTimeSlotBase or FKTimeSlotPunctual
ALTER TABLE Appointment ADD CONSTRAINT checkTimeSlot CHECK ((FKTimeSlotBase IS NULL AND FKTimeSlotPunctual IS NOT NULL) OR (FKTimeSlotBase IS NOT NULL AND FKTimeSlotPunctual IS NULL));


-- Trigger
-- ────────────────────────────────────────────────────────────
-- Hash the password of an Interpreter on INSERT or UPDATE.
-- The hash is only recomputed on UPDATE if the password field
-- has actually changed, to avoid unnecessary rehashing.
-- Algorithm: SHA256 via Oracle STANDARD_HASH.
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_hash_password_interprete
BEFORE INSERT OR UPDATE ON Interpreter
    FOR EACH ROW
        DECLARE
            hash_pwd VARCHAR2(255);
        BEGIN
            IF INSERTING OR (UPDATING AND :NEW.password != :OLD.password) THEN
                SELECT STANDARD_HASH(:NEW.password, 'SHA256')
                INTO hash_pwd
                FROM dual;
                :NEW.password := hash_pwd;
            END IF;
        END;
/

-- ────────────────────────────────────────────────────────────
-- Hash the password of a Beneficiary on INSERT or UPDATE.
-- Algorithm: SHA256 via Oracle STANDARD_HASH.
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_hash_password_beneficiary
BEFORE INSERT OR UPDATE ON Beneficiary
    FOR EACH ROW
        DECLARE
            hash_pwd VARCHAR2(255);
        BEGIN
            IF INSERTING OR (UPDATING AND :NEW.password != :OLD.password) THEN
                SELECT STANDARD_HASH(:NEW.password, 'SHA256')
                INTO hash_pwd
                FROM dual;
                :NEW.password := hash_pwd;
            END IF;
        END;
/

-- ────────────────────────────────────────────────────────────
-- Shared sequence used to generate unique login numbers
-- for Interpreters, Coordinators and Beneficiaries.
-- Format: I0001, C0001, B0001 (prefix + 4-digit padded number).
-- ────────────────────────────────────────────────────────────
CREATE SEQUENCE seq_userlexia_login
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ────────────────────────────────────────────────────────────
-- Auto-generate the login of an Interpreter on INSERT
-- if no login was provided.
-- Format: 'I' followed by a 4-digit zero-padded sequence number.
-- Example: I0001, I0002, I0042
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_generate_login_interpreter
BEFORE INSERT ON Interpreter
FOR EACH ROW
DECLARE
    v_seq_num NUMBER(10);
BEGIN
    IF :NEW.login IS NULL THEN
        v_seq_num := SEQ_USERLEXIA_LOGIN.NEXTVAL;

            :NEW.login := 'I' || LPAD(v_seq_num, 4, '0');

    END IF;
END;
/

-- ────────────────────────────────────────────────────────────
-- Auto-generate the login of a Coordinator on INSERT.
-- Updates the login of the linked Interpreter row to use
-- the 'C' prefix instead of 'I', since a Coordinator
-- is stored as an Interpreter with an elevated role.
-- Format: 'C' followed by a 4-digit zero-padded sequence number.
-- Example: C0003, C0007
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_generate_login_coordinator
BEFORE INSERT ON Coordinator
FOR EACH ROW
BEGIN
    UPDATE Interpreter
    SET login = 'C' || SUBSTR(login, 2)
    WHERE numInterpreter = :NEW.FKnumInterpreter;
END;
/

-- ────────────────────────────────────────────────────────────
-- Auto-generate the login of a Beneficiary on INSERT
-- if no login was provided.
-- Format: 'B' followed by a 4-digit zero-padded sequence number.
-- Example: B0001, B0002, B0099
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_generate_login_beneficiairy
BEFORE INSERT ON Beneficiary
FOR EACH ROW
DECLARE
    v_seq_num NUMBER(10);
BEGIN
    IF :NEW.login IS NULL THEN
        v_seq_num := SEQ_USERLEXIA_LOGIN.NEXTVAL;
            :NEW.login := 'B' || LPAD(v_seq_num, 4, '0');

    END IF;
END;
/


-- ────────────────────────────────────────────────────────────
-- Delete an Appointment
-- Dependencies: RequiredAcademicSkill, RequiredProfessionalSkill, RDVInterpreter
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_delete_appointment
BEFORE DELETE ON Appointment
FOR EACH ROW
BEGIN
    DELETE FROM RequiredAcademicSkill     WHERE numAppointment = :OLD.numAppointment;
    DELETE FROM RequiredProfessionalSkill WHERE numAppointment = :OLD.numAppointment;
    DELETE FROM RDVInterpreter            WHERE numAppointment = :OLD.numAppointment;
END;
/


-- ────────────────────────────────────────────────────────────
-- Delete a Beneficiary
-- Dependencies: Appointment
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_delete_beneficiary
BEFORE DELETE ON Beneficiary
FOR EACH ROW
BEGIN
    DELETE FROM Appointment WHERE FKnumBeneficiary = :OLD.numBeneficiary;
END;
/


-- ────────────────────────────────────────────────────────────
-- Delete an Interpreter
-- Dependencies: Absence, Coordinator, RDVInterpreter,
--               AcademicSkillInterpreter, ProfessionalSkillInterpreter,
--               Beneficiary.FKnumInterpreter
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_delete_interpreter
BEFORE DELETE ON Interpreter
FOR EACH ROW
BEGIN
    DELETE FROM Absence                  WHERE FKnumInterpreter = :OLD.numInterpreter;

    DELETE FROM Coordinator              WHERE FKnumInterpreter = :OLD.numInterpreter;

    DELETE FROM RDVInterpreter           WHERE numInterpreter   = :OLD.numInterpreter;

    DELETE FROM AcademicSkillInterpreter     WHERE numInterpreter = :OLD.numInterpreter;

    DELETE FROM ProfessionalSkillInterpreter WHERE numInterpreter = :OLD.numInterpreter;

    UPDATE Beneficiary SET FKnumInterpreter = NULL WHERE FKnumInterpreter = :OLD.numInterpreter;
END;
/


-- ────────────────────────────────────────────────────────────
-- Delete an AcademicSkill
-- Dependencies: AcademicSkillInterpreter, RequiredAcademicSkill
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_delete_academic_skill
BEFORE DELETE ON AcademicSkill
FOR EACH ROW
BEGIN
    DELETE FROM AcademicSkillInterpreter WHERE numAcademicSkill = :OLD.numAcademicSkill;
    DELETE FROM RequiredAcademicSkill    WHERE numAcademicSkill = :OLD.numAcademicSkill;
END;
/


-- ────────────────────────────────────────────────────────────
-- Delete a ProfessionalSkill
-- Dependencies: ProfessionalSkillInterpreter, RequiredProfessionalSkill
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_delete_professional_skill
BEFORE DELETE ON ProfessionalSkill
FOR EACH ROW
BEGIN
    DELETE FROM ProfessionalSkillInterpreter WHERE numProfessionalSkill = :OLD.numProfessionalSkill;
    DELETE FROM RequiredProfessionalSkill    WHERE numProfessionalSkill = :OLD.numProfessionalSkill;
END;
/


-- ────────────────────────────────────────────────────────────
-- Delete a TimeSlotBase
-- Dependencies: Absence, Appointment
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_delete_timeslot_base
BEFORE DELETE ON TimeSlotBase
FOR EACH ROW
BEGIN
    DELETE FROM Absence     WHERE FKTimeSlotBase = :OLD.numTimeSlot;
    DELETE FROM Appointment WHERE FKTimeSlotBase = :OLD.numTimeSlot;
END;
/


-- ────────────────────────────────────────────────────────────
-- Delete a TimeSlotPunctual
-- Dependencies: Absence, Appointment
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_delete_timeslot_punctual
BEFORE DELETE ON TimeSlotPunctual
FOR EACH ROW
BEGIN
    DELETE FROM Absence     WHERE FKTimeSlotPunctual = :OLD.numTimeSlot;
    DELETE FROM Appointment WHERE FKTimeSlotPunctual = :OLD.numTimeSlot;
END;
/


-- ────────────────────────────────────────────────────────────
-- Delete a Referrer
-- Dependencies: Work
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_delete_referrer
BEFORE DELETE ON Referrer
FOR EACH ROW
BEGIN
    DELETE FROM Work WHERE numReferer = :OLD.numReferer;
END;
/


-- ────────────────────────────────────────────────────────────
-- Delete an Establishment
-- Dependencies: Appointment, Work, Referrer
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_delete_establishment
BEFORE DELETE ON Establishment
FOR EACH ROW
BEGIN
    DELETE FROM Appointment WHERE FKnumEstablishment = :OLD.numEstablishment;

    DELETE FROM Work     WHERE numEstablishment  = :OLD.numEstablishment;

    DELETE FROM Referrer WHERE FKEstablishment   = :OLD.numEstablishment;
END;
/


-- ────────────────────────────────────────────────────────────
-- Delete an Address
-- Dependencies: Establishment
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER trg_delete_address
BEFORE DELETE ON Address
FOR EACH ROW
BEGIN
    DELETE FROM Establishment WHERE FKAddress = :OLD.numAddress;
END;
/
