using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Mail;
using System.Text;

namespace Projet_app_principale {
    public class Email {
        public string emailSender { get; private set; }
        public string emailReceiver { get; private set; }
        public string host { get; private set; }

        public string password { get; private set; }
        public int port { get; private set; }
        public string name { get; private set; }
        public string ipAddress { get; private set; }
        public string status { get; private set; }
        public bool ssl { get; private set; }
        /// <summary>
        /// Constructs an Email object by copying all the fields from BackupSetting useful for SMTP relay and sending an email.
        /// </summary>
        /// <param name="configSetting">The global config</param>
        /// <param name="name">The name of the device</param>
        /// <param name="ipAddress">The ipAddress of the device<param>
        /// <param name="status">The status of the device<param>
        /// <param name="ssl">True, the ssl param is enabled, false, otherwise<param>
        public Email(ConfigSetting configSetting, string name, string ipAddress, string status, bool ssl) {
            emailSender = configSetting.SMTPEmail;
            emailReceiver = configSetting.EmailSenderUsers;
            host = configSetting.SMTPHost;
            port = configSetting.SMTPPort;
            password = configSetting.SMTPPassword;
            this.name = name;
            this.ipAddress = ipAddress;
            this.status = status;
            this.ssl = ssl;
        }
        /// <summary>
        /// Generates the email message 
        /// </summary>
        /// <returns>the email message</returns>
        public string GenerateMessageBody() {
            string message = $"""
                <p style='font-size: 16px;'>The device with the name <u><b>{name}</b></u><br>
                and the IP address <u><b>{ipAddress} </b></u><br>
                is now <u><b>{status.ToLower()}</b></u>.</p>
                """;
            return message;
        }
        /// <summary>
        /// Sends the result message generated by generateMessageBody() using SMTP.
        /// if ssl param is true, EnableSSl is true
        /// </summary>
        public async Task Send() {
            SmtpClient client = new SmtpClient();
            client.Host = host;
            client.Port = port;
            client.Credentials = new NetworkCredential(emailSender, password);
            client.DeliveryMethod = SmtpDeliveryMethod.Network;
            client.EnableSsl = ssl;
            MailMessage message = new MailMessage(emailSender, emailReceiver);
            message.IsBodyHtml = true;
            message.Body = GenerateMessageBody();
            message.BodyEncoding = System.Text.Encoding.UTF8;
            message.Subject = "⚠️ "+ name + " device state change on " + DateTime.Now.ToString("dd'/'MM'/'yyyy 'at' HH:mm:ss ");
            message.SubjectEncoding = System.Text.Encoding.UTF8;
            await client.SendMailAsync(message);
        }

    }
}
