using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Mail;
using System.Text;
using static System.Net.Mime.MediaTypeNames;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.ListView;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.TrackBar;

namespace BackupAndClean {
    public class Email {
        public string emailSender { get; private set; }
        public string emailReceiver { get; private set; }
        public string host { get; private set; }

        public string password { get; private set; }
        public int port { get; private set; }
        public string textReturnClean { get; private set; }
        public string textReturnBackup { get; private set; }
        /// <summary>
        /// Constructs an Email object by copying all the fields from BackupSetting useful for SMTP relay and sending an email.
        /// </summary>
        /// <param name="backupSetting">The global config</param>
        /// <param name="textReturnBackup">The status text of the backup task</param>
        /// <param name="textReturnClean">The status text of the clean task<param>
        public Email(BackupSetting backupSetting, string textReturnBackup, string textReturnClean)
        {
            emailSender = backupSetting.SMTPEmail;
            emailReceiver = backupSetting.EmailSenderUsers;
            host = backupSetting.SMTPHost;
            port = backupSetting.SMTPPort;
            password = backupSetting.SMTPPassword;
            this.textReturnBackup = textReturnBackup;
            this.textReturnClean = textReturnClean;
        }
        /// <summary>
        /// Generates the email message using the text from the two tasks
        /// </summary>
        /// <returns>the email message</returns>
        public string generateMessageBody()
        {
            string message = $"""
                Résultat de la backup : 
                    {textReturnBackup}
                    
                Résultat du nettoyage : 
                    {textReturnClean}
                """;
            return message;
        }
        /// <summary>
        /// Sends the result message generated by generateMessageBody() from the 2 tasks to the recipient using SMTP.
        /// </summary>
        public void send()
        {
            SmtpClient client = new SmtpClient();
            client.Host = host;
            client.Port = port;
            client.Credentials = new NetworkCredential(emailSender, password);
            client.DeliveryMethod = SmtpDeliveryMethod.Network;
            client.EnableSsl = true;
            MailMessage message = new MailMessage(emailSender, emailReceiver);
            message.Body = generateMessageBody();
            message.BodyEncoding = System.Text.Encoding.UTF8;
            message.Subject = "Résultats d'execution de Sauvegarde et Nettoyage du " + DateTime.Now.ToString();
            message.SubjectEncoding = System.Text.Encoding.UTF8;
            client.Send(message);
        }

    }
}
