package be.hers.info.ProjetIntegree.DAO;

import be.hers.info.ProjetIntegree.POJO.Address;
import be.hers.info.ProjetIntegree.POJO.Establishment;
import oracle.jdbc.OracleTypes;
import oracle.jdbc.internal.OraclePreparedStatement;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Rosman Loïs
 * @reviewer Nicolas Jean-François, Louis Halet, Wellinger Chloé
 */
public class DAOAddress extends DAO<Address> {

    /**
     * Searches for an Address by its numAddress.
     * The Establishment linked to the Address is loaded via DAOEstablishment.
     *
     * @param objectToSearchInDB the numAddress of the Address to search for
     * @return The Address if found, null otherwise
     * @throws SQLException In case of any SQL problems encountered with this method
     */
    @Override
    public Address find(int objectToSearchInDB) throws SQLException {
        Address addressFind = null;
        String query = """
                SELECT * 
                FROM Address 
                WHERE numAddress = ?
                """;
        PreparedStatement prStat = null;
        ResultSet rs = null;
        try {
            prStat = connect.prepareStatement(query);
            prStat.setInt(1, objectToSearchInDB);
            rs = prStat.executeQuery();

            if (rs.next()) {
                DAOEstablishment daoEstablishment = new DAOEstablishment();
                Establishment establishmentFind = daoEstablishment.find(objectToSearchInDB);
                addressFind = new Address(rs.getInt("numAddress"), rs.getInt("postalCode"),
                        rs.getString("postalBox"), rs.getString("locality"),
                        rs.getString("hamlet"), establishmentFind);
            }
        } finally {
            closeStatementAndResultSet(prStat, rs);
        }

        return addressFind;
    }

    /**
     * Creates a list containing all the Addresses in the Address table.
     * For each Address, the linked Establishment is loaded via DAOEstablishment.
     *
     * @return A list containing all the Addresses, or an empty list if the table is empty
     * @throws SQLException In case of any SQL problems encountered with this method
     */
    @Override
    public List<Address> findAll() throws SQLException {
        List<Address> listAddressFind = new ArrayList<>();
        String query = """
                SELECT * 
                FROM Address
                """;
        PreparedStatement prStat = null;
        ResultSet rs = null;
        try {
            prStat = connect.prepareStatement(query);
            rs = prStat.executeQuery();

            while (rs.next()) {
                DAOEstablishment daoEstablishment = new DAOEstablishment();
                Establishment establishmentFind = daoEstablishment.find(rs.getInt("NumAddress"));
                Address addressFind = new Address(rs.getInt("NumAddress"), rs.getInt("postalCode"),
                        rs.getString("postalBox"), rs.getString("locality"),
                        rs.getString("hamlet"),
                        establishmentFind);
                listAddressFind.add(addressFind);
            }
        } finally {
            closeStatementAndResultSet(prStat, rs);
        }

        return listAddressFind;
    }

    /**
     * Inserts the Address passed as a parameter into the Address table.
     * The numAddress is auto-generated by Oracle and retrieved via RETURNING INTO.
     * Precondition: the Address passed as a parameter cannot be null.
     *
     * @param objectToInsertInDB the Address to be inserted into the table
     * @return true if the Address was successfully inserted, false otherwise
     * @throws SQLException In case of any SQL problems encountered with this method
     */
    @Override
    public boolean create(Address objectToInsertInDB) throws SQLException {
        boolean isInserted = false;
        OraclePreparedStatement prStat = null;
        ResultSet generateID = null;

        String query = """
                INSERT INTO Address (postalCode, postalBox, locality, hamlet)
                VALUES (?, ?, ?, ?) 
                RETURNING numAddress INTO ?
                """;

        try {
            prStat = (OraclePreparedStatement) connect.prepareStatement(query);
            prStat.setInt(1, objectToInsertInDB.getPostcode());
            prStat.setString(2, objectToInsertInDB.getPostOfficeBox());
            prStat.setString(3, objectToInsertInDB.getLocality());
            prStat.setString(4, objectToInsertInDB.getHamlet());
            prStat.registerReturnParameter(5, OracleTypes.INTEGER);

            if (prStat.executeUpdate() > 0) {
                generateID = prStat.getReturnResultSet();
                if (!generateID.next()) {
                    throw new SQLException("[DAOAddress] Impossible de récupérer le numAddress généré.");
                }
                int numAddressGenerated = generateID.getInt(1);
                objectToInsertInDB.setNumAddress(numAddressGenerated);

                isInserted = true;
            }

        } finally {
            closeStatementAndResultSet(prStat, generateID);
        }
        return isInserted;
    }

    /**
     * Updates all Address fields in the table except its numAddress.
     * Precondition: the Address passed as a parameter cannot be null.
     *
     * @param objectToUpdateInDB the Address containing the numAddress and the fields to update
     * @return true if the Address was successfully updated, false otherwise
     * @throws SQLException In case of any SQL problems encountered with this method
     */
    @Override
    public boolean update(Address objectToUpdateInDB) throws SQLException {
        boolean isUpdated = false;
        String query = """
                UPDATE Address 
                SET postalCode = ?, postalBox = ? , locality = ?, hamlet = ? 
                WHERE numAddress = ?
                """;

        PreparedStatement prStat = null;
        try {
            prStat = connect.prepareStatement(query);
            prStat.setInt(1, objectToUpdateInDB.getPostcode());
            prStat.setString(2, objectToUpdateInDB.getPostOfficeBox());
            prStat.setString(3, objectToUpdateInDB.getLocality());
            prStat.setString(4, objectToUpdateInDB.getHamlet());
            prStat.setInt(5, objectToUpdateInDB.getNumAddress());

            if (prStat.executeUpdate() > 0)
                isUpdated = true;
        } finally {
            closeStatement(prStat);
        }

        return isUpdated;
    }

    /**
     * Deletes the Address whose numAddress matches the numAddress of the Address passed as a parameter.
     * Precondition: the Address passed as a parameter cannot be null.
     *
     * @param objectToDeleteFormDB the Address to be deleted from the table
     * @return true if the Address was successfully deleted, false otherwise
     * @throws SQLException In case of any SQL problems encountered with this method
     */
    @Override
    public boolean delete(Address objectToDeleteFormDB) throws SQLException {
        boolean isDeleted = false;

        String query = """
                DELETE FROM Address 
                WHERE NumAddress = ?
                """;

        PreparedStatement prStat = null;
        try {
            prStat = connect.prepareStatement(query);
            prStat.setInt(1, objectToDeleteFormDB.getNumAddress());

            if (prStat.executeUpdate() > 0)
                isDeleted = true;
        } finally {
            closeStatement(prStat);
        }

        return isDeleted;
    }

    /**
     * Searches for all Address objects linked to a given Establishment name.
     * The Establishment object is not loaded (lazy loading).
     *
     * @param establishmentName the name of the Establishment
     * @return a list of Address linked to the Establishment,
     * or an empty list if none are found
     * @throws SQLException in case of any SQL problems encountered with this method
     */
    public List<Address> findAllByEstablishment(String establishmentName) throws SQLException {
        String query = """
                SELECT a.numAddress, a.postalCode, a.postalBox, a.locality, a.hamlet
                FROM Address a
                JOIN Establishment e
                ON e.FKAddress = a.numAddress
                WHERE e.name = ?
                """;
        List<Address> addressList = new ArrayList<>();
        PreparedStatement prStat = null;
        ResultSet rs = null;

        try {
            prStat = connect.prepareStatement(query);
            prStat.setString(1, establishmentName);
            rs = prStat.executeQuery();

            while (rs.next()) {
                Address address = new Address();
                address.setNumAddress(rs.getInt("numAddress"));
                address.setPostcode(rs.getInt("postalCode"));
                address.setPostOfficeBox(rs.getString("postalBox"));
                address.setLocality(rs.getString("locality"));
                address.setHamlet(rs.getString("hamlet"));
                addressList.add(address);
            }
        } finally {
            closeStatementAndResultSet(prStat, rs);
        }
        return addressList;
    }
}