package be.hers.info.ProjetIntegree.DAO;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import be.hers.info.ProjetIntegree.POJO.*;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleTypes;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Vatafu Jean
 * @reviewer Nicolas Jean-François, Louis Halet
 */
public class DAOAbsence extends DAO<Absence> {
    private static final Logger logger = LoggerFactory.getLogger(DAOAbsence.class);

    /**
     * Searches for an Absence by its numAbsence.
     * The TimeSlotPunctual is loaded via DAOTimeSlotPunctual
     *
     * @param objectToSearchInDB the numAbsence to search for
     * @return The Absence if found, null otherwise
     * @throws SQLException In case of any SQL problems encountered with this method
     */
    public Absence find(int objectToSearchInDB) throws SQLException {
        Absence absence = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;

        String query = "SELECT status, reasons, privateReason, FKTimeSlotBase, FKTimeSlotPunctual " +
                "FROM Absence " +
                "WHERE numAbsence = ?";

        try {
            preparedStatement = connect.prepareStatement(query);
            preparedStatement.setInt(1, objectToSearchInDB);

            resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                TimeSlot timeSlot = null;

                if (resultSet.getObject("FKTimeSlotBase") != null) {
                    DAOTimeSlotBase daoTimeSlotBase = new DAOTimeSlotBase();
                    timeSlot = daoTimeSlotBase.find(resultSet.getInt("FKTimeSlotBase"));
                } else {
                    DAOTimeSlotPunctual daoTimeSlotPunctual = new DAOTimeSlotPunctual();
                    timeSlot = daoTimeSlotPunctual.find(resultSet.getInt("FKTimeSlotPunctual"));
                }

                absence = new Absence(objectToSearchInDB, resultSet.getString("status"), timeSlot,
                        resultSet.getString("reasons"), resultSet.getBoolean("privateReason"));
            }
        } catch (BadStatusException e) {
            logger.error("Statut invalide pour l'absence {}", objectToSearchInDB, e);
        } finally {
            closeStatementAndResultSet(preparedStatement, resultSet);
        }
        return absence;
    }

    /**
     * Creates a list containing all the Absence in the Absence table
     * For each Absence, the TimeSlotPunctual is loaded via DAOTimeSlotPunctual
     *
     * @return A list containing all the Absence, or an empty list if the table is empty
     * @throws SQLException In case of any SQL problems encountered with this method
     */
    public List<Absence> findAll() throws SQLException {
        List<Absence> absenceList = new ArrayList<Absence>();
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;

        String query = "SELECT numAbsence, status, reasons, privateReason, FKTimeSlotBase, FKTimeSlotPunctual " +
                "FROM Absence";

        try {
            preparedStatement = connect.prepareStatement(query);
            resultSet = preparedStatement.executeQuery();

            DAOTimeSlotPunctual daoTimeSlotPunctual = new DAOTimeSlotPunctual();
            DAOTimeSlotBase daoTimeSlotBase = new DAOTimeSlotBase();
            TimeSlot timeSlot = null;

            while (resultSet.next()) {
                if (resultSet.getObject("FKTimeSlotBase") != null) {
                    timeSlot = daoTimeSlotBase.find(resultSet.getInt("FKTimeSlotBase"));
                } else {
                    timeSlot = daoTimeSlotPunctual.find(resultSet.getInt("FKTimeSlotPunctual"));
                }

                Absence absence = new Absence(resultSet.getInt("numAbsence"), resultSet.getString("status"),
                        timeSlot, resultSet.getString("reasons"), resultSet.getBoolean("privateReason"));

                absenceList.add(absence);
            }
        } catch (BadStatusException e) {
            logger.error("Statut invalide lors du chargement de toutes les absences", e);
            e.printStackTrace();
        } finally {
            closeStatementAndResultSet(preparedStatement, resultSet);
        }
        return absenceList;
    }

    /**
     * Adds the Absence passed as a parameter to the Absence table without any associated User
     * The numAbsence is auto-generated by Oracle
     * Precondition: the Absence passed as a parameter cannot be null
     * Precondition: the TimeSlot of the Absence must already exist in the database
     *
     * @param objectToInsertInDB the Absence to be inserted into the table
     * @return true if the Absence is successfully inserted, false otherwise
     * @throws SQLException In case of any SQL problems encountered with this method
     */
    public boolean create(Absence objectToInsertInDB) throws SQLException {
        boolean isCreated = false;
        OraclePreparedStatement preparedStatement = null;
        ResultSet generateID = null;

        String query = "INSERT INTO Absence(status, reasons, privateReason, FKTimeSlotBase, FKTimeSlotPunctual, FKnumInterpreter) " +
                "VALUES (?, ?, ?, ?, ?, ?) " +
                "RETURNING numAbsence  INTO ?";

        try {
            preparedStatement = (OraclePreparedStatement) connect.prepareStatement(query);

            preparedStatement.setString(1, objectToInsertInDB.getStatus());
            preparedStatement.setString(2, objectToInsertInDB.getReason());
            preparedStatement.setBoolean(3, objectToInsertInDB.isPrivateReason());

            if (objectToInsertInDB.getTimeSlot() instanceof TimeSlotBase) {
                preparedStatement.setInt(4, objectToInsertInDB.getTimeSlot().getNumTimeSlot());
                preparedStatement.setNull(5, java.sql.Types.INTEGER);
            } else {
                preparedStatement.setNull(4, java.sql.Types.INTEGER);
                preparedStatement.setInt(5, objectToInsertInDB.getTimeSlot().getNumTimeSlot());
            }

            preparedStatement.setNull(6, java.sql.Types.INTEGER);

            preparedStatement.registerReturnParameter(7, OracleTypes.INTEGER);

            if (preparedStatement.executeUpdate() > 0) {
                generateID = preparedStatement.getReturnResultSet();
                if (!generateID.next()) {
                    throw new SQLException("[DAOAbsence] Impossible de récupérer le ID généré");
                }

                int numAbsenceGenerated = generateID.getInt(1);
                objectToInsertInDB.setNumAbsence(numAbsenceGenerated);

                isCreated = true;
            }
        } finally {
            closeStatementAndResultSet(preparedStatement, generateID);
        }
        return isCreated;
    }

    /**
     * Adds the Absence passed as a parameter to the Absence table,
     * then inserts its Interpreter via an additinal parameter
     * Precondition: the Absence passed as a parameter cannot be null
     * Precondition: the TimeSlot of the Absence must already exist in the database
     * Precondition: the Interpreter must already exist in the database
     *
     * @param objectToInsertInDB the Absence to be inserted into the table
     * @return true if the Absence is successfully inserted, false otherwise
     * @throws SQLException In case of any SQL problems encountered with this method
     */
    public boolean create(Absence objectToInsertInDB, int otherObjectID) throws SQLException, IllegalArgumentException {
        boolean isCreated = false;
        OraclePreparedStatement preparedStatement = null;
        ResultSet generateID = null;

        String query = "INSERT INTO Absence(status, reasons, privateReason, FKTimeSlotBase, FKTimeSlotPunctual, FKnumInterpreter) " +
                "VALUES (?, ?, ?, ?, ?, ?) " +
                "RETURNING numAbsence  INTO ?";

        try {
            preparedStatement = (OraclePreparedStatement) connect.prepareStatement(query);

            preparedStatement.setString(1, objectToInsertInDB.getStatus());
            preparedStatement.setString(2, objectToInsertInDB.getReason());
            preparedStatement.setBoolean(3, objectToInsertInDB.isPrivateReason());

            if (objectToInsertInDB.getTimeSlot() instanceof TimeSlotBase) {
                preparedStatement.setInt(4, objectToInsertInDB.getTimeSlot().getNumTimeSlot());
                preparedStatement.setNull(5, java.sql.Types.INTEGER);
            } else {
                preparedStatement.setNull(4, java.sql.Types.INTEGER);
                preparedStatement.setInt(5, objectToInsertInDB.getTimeSlot().getNumTimeSlot());
            }

            preparedStatement.setInt(6, otherObjectID);

            preparedStatement.registerReturnParameter(7, OracleTypes.INTEGER);

            if (preparedStatement.executeUpdate() > 0) {
                generateID = preparedStatement.getReturnResultSet();
                if (!generateID.next()) {
                    throw new SQLException("[DAOAbsence] Impossible de récupérer le ID généré");
                }

                int numAbsenceGenerated = generateID.getInt(1);
                objectToInsertInDB.setNumAbsence(numAbsenceGenerated);

                isCreated = true;
            }
        } finally {
            closeStatementAndResultSet(preparedStatement, generateID);
        }
        return isCreated;
    }

    /**
     * Updates status Absence fields in the table except its id
     * Precondition: the Absence passed as a parameter cannot be null
     *
     * @param objectToUpdateInDB the Absence to update
     * @return true if the Absence was successfully updated, false otherwise
     * @throws SQLException In case of any SQL problems encountered with this method
     */
    public boolean update(Absence objectToUpdateInDB) throws SQLException {
        boolean updated = false;
        PreparedStatement preparedStatement = null;

        String query = "UPDATE Absence " +
                "SET status = ?, reasons = ?, privateReason = ?, FKTimeSlotBase = ?, FKTimeSlotPunctual = ? " +
                "WHERE numAbsence = ?";

        try {
            preparedStatement = connect.prepareStatement(query);

            preparedStatement.setString(1, objectToUpdateInDB.getStatus());
            preparedStatement.setString(2, objectToUpdateInDB.getReason());
            preparedStatement.setBoolean(3, objectToUpdateInDB.isPrivateReason());

            if (objectToUpdateInDB.getTimeSlot() instanceof TimeSlotBase) {
                preparedStatement.setInt(4, objectToUpdateInDB.getTimeSlot().getNumTimeSlot());
                preparedStatement.setNull(5, java.sql.Types.INTEGER);
            } else {
                preparedStatement.setNull(4, java.sql.Types.INTEGER);
                preparedStatement.setInt(5, objectToUpdateInDB.getTimeSlot().getNumTimeSlot());
            }

            preparedStatement.setInt(6, objectToUpdateInDB.getNumAbsence());

            if (preparedStatement.executeUpdate() > 0) {
                updated = true;
            }
        } finally {
            closeStatement(preparedStatement);
        }
        return updated;
    }

    /**
     * Deletes the Absence whose numAbsence matches the numAbsence
     * Precondition: the Absence passed as a parameter cannot be null
     *
     * @param objectToDeleteFormDB the Absence to be deleted from the table
     * @return true if the Absence was successfully deleted, false otherwise
     * @throws SQLException In case of any SQL problems encountered with this method
     */
    public boolean delete(Absence objectToDeleteFormDB) throws SQLException {
        boolean isDeleted = false;
        PreparedStatement preparedStatement = null;

        String query = "DELETE FROM Absence " +
                "WHERE numAbsence = ?";

        try {
            preparedStatement = connect.prepareStatement(query);

            preparedStatement.setInt(1, objectToDeleteFormDB.getNumAbsence());

            if (preparedStatement.executeUpdate() > 0) {
                isDeleted = true;
            }
        } finally {
            closeStatement(preparedStatement);
        }
        return isDeleted;
    }

    /**
     * Retrieves a list of punctual absences for a specific interpreter within a given date range
     * Each Absence is populated with its corresponding TimeSlotPunctual details
     *
     * @param interpreter The interpreter whose absences are being searched
     * @return A list of Absence objects matching the criteria, or an empty list if no absences are found
     * @throws SQLException       If a database access error occurs or the SQL query fails
     * @throws BadStatusException If the absence status in the database does not match
     *                            the expected values ('en attente', 'refuse', or 'accepte')
     */
    public List<Absence> findPunctualAbsencesInterpreter(Interpreter interpreter) throws SQLException, BadStatusException {
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        List<Absence> punctualAbsenceList = new ArrayList<Absence>();

        String query = "SELECT ab.numAbsence, ab.status, ab.reasons, ab.privateReason, ab.FKTimeSlotPunctual " +
                "FROM Absence ab " +
                "JOIN TimeSlotPunctual tsp ON ab.FKTimeSlotPunctual = tsp.numTimeSlot " +
                "WHERE ab.FKnumInterpreter = ?";
        try {
            preparedStatement = connect.prepareStatement(query);

            preparedStatement.setInt(1, interpreter.getNumInterpreter());

            resultSet = preparedStatement.executeQuery();

            DAOTimeSlotPunctual daoTimeSlotPunctual = new DAOTimeSlotPunctual();
            while (resultSet.next()) {
                TimeSlot timeSlot = daoTimeSlotPunctual.find(resultSet.getInt("FKTimeSlotPunctual"));

                try {
                    Absence absence = new Absence(resultSet.getInt("numAbsence"),
                            resultSet.getString("status"), timeSlot, resultSet.getString("reasons"),
                            resultSet.getBoolean("privateReason"));

                    punctualAbsenceList.add(absence);
                } catch (BadStatusException e) {
                    throw new BadStatusException("[DAOAbsence] Le statut ne peut etre que 'en attente', 'refuse' ou 'accepte'");
                }
            }
        } finally {
            closeStatementAndResultSet(preparedStatement, resultSet);
        }
        return punctualAbsenceList;
    }

    /**
     * Retrieves all recurring base absences for a specific interpreter
     * This method joins the Absence table with TimeSlotBase and populates each
     * Absence object with its corresponding base time slot details
     *
     * @param interpreter The interpreter whose base absences are being retrieved
     * @return A list containing all base Absence objects found, or an empty list if none exist
     * @throws SQLException       If a database access error occurs during the process.
     * @throws BadStatusException If the absence status in the database does not match
     *                            the expected values ('en attente', 'refuse', or 'accepte')
     */
    public List<Absence> findBaseAbsencesInterpreter(Interpreter interpreter) throws SQLException, BadStatusException {
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        List<Absence> baseAbsenceList = new ArrayList<Absence>();

        String query = "SELECT ab.numAbsence, ab.status, ab.reasons, ab.privateReason, ab.FKTimeSlotBase " +
                "FROM Absence ab " +
                "JOIN TimeSlotBase tsb ON ab.FKTimeSlotBase = tsb.numTimeSlot " +
                "WHERE ab.FKnumInterpreter = ?";

        try {
            preparedStatement = connect.prepareStatement(query);

            preparedStatement.setInt(1, interpreter.getNumInterpreter());

            resultSet = preparedStatement.executeQuery();

            DAOTimeSlotBase daoTimeSlotBase = new DAOTimeSlotBase();
            while (resultSet.next()) {
                TimeSlot timeSlot = daoTimeSlotBase.find(resultSet.getInt("FKTimeSlotBase"));

                try {
                    Absence absence = new Absence(resultSet.getInt("numAbsence"), resultSet.getString("status"),
                            timeSlot, resultSet.getString("reasons"), resultSet.getBoolean("privateReason"));

                    baseAbsenceList.add(absence);
                } catch (BadStatusException e) {
                    throw new BadStatusException("[DAOAbsence] Le statut ne peut etre que 'en attente', 'refuse' ou 'accepte'");
                }

            }
        } finally {
            closeStatementAndResultSet(preparedStatement, resultSet);
        }

        return baseAbsenceList;
    }

    /**
     * Retrieves all punctual absences (with a TimeSlotPunctual) with status "en attente", across all interpreters.
     * Each Absence is populated with its corresponding TimeSlotPunctual and interpreter details.
     *
     * @return a list of Absence with status "en attente", or an empty list if none found
     * @throws SQLException       If a database access error occurs or the SQL query fails
     * @throws BadStatusException If the absence status in the database does not match
     *                            the expected values ('en attente', 'refuse', or 'accepte')
     */
    public List<Absence> findAllPendingAbsences() throws SQLException, BadStatusException {
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        List<Absence> pendingAbsenceList = new ArrayList<>();

        String query = "SELECT ab.numAbsence, ab.status, ab.reasons, ab.privateReason, " +
                "ab.FKTimeSlotPunctual, ab.FKnumInterpreter " +
                "FROM Absence ab " +
                "JOIN TimeSlotPunctual tsp ON ab.FKTimeSlotPunctual = tsp.numTimeSlot " +
                "WHERE ab.status = 'en attente' " +
                "AND ab.FKnumInterpreter IS NOT NULL";

        try {
            preparedStatement = connect.prepareStatement(query);
            resultSet = preparedStatement.executeQuery();

            DAOTimeSlotPunctual daoTimeSlotPunctual = new DAOTimeSlotPunctual();
            DAOInterpreter daoInterpreter = new DAOInterpreter();

            while (resultSet.next()) {
                TimeSlot timeSlot = daoTimeSlotPunctual.find(resultSet.getInt("FKTimeSlotPunctual"));

                try {
                    Absence absence = new Absence(
                            resultSet.getInt("numAbsence"),
                            resultSet.getString("status"),
                            timeSlot,
                            resultSet.getString("reasons"),
                            resultSet.getBoolean("privateReason")

                    );
                    absence.setInterpreter(daoInterpreter.find(resultSet.getInt("FKnumInterpreter")));
                    pendingAbsenceList.add(absence);
                } catch (BadStatusException e) {
                    throw new BadStatusException("[DAOAbsence] Le statut ne peut etre que 'en attente', 'refuse' ou 'accepte'");
                }
            }
        } finally {
            closeStatementAndResultSet(preparedStatement, resultSet);
        }
        return pendingAbsenceList;
    }
}
