package be.hers.info.ProjetIntegree.DAO;

import be.hers.info.ProjetIntegree.POJO.ProfessionalSkill;

import java.sql.PreparedStatement;

import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleTypes;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Wellinger Chloé
 * @reviewer Nicolas Jean-François, Halet Louis
 */
public class DAOProfessionalSkill extends DAO<ProfessionalSkill> {

    /**
     * Searches for a ProfessionalSkill by its numProfessionalSkill.
     *
     * @param idToSearch the numProfessionalSkill of the ProfessionalSkill to search for.
     * @return The ProfessionalSkill if found, null otherwise.
     * @throws SQLException In case of any SQL problems encountered with this method.
     */
    @Override
    public ProfessionalSkill find(int idToSearch) throws SQLException {
        PreparedStatement prStat = null;
        ResultSet rs = null;
        ProfessionalSkill professionalSkillFind = null;

        String query = "SELECT numProfessionalSkill, designation " +
                "FROM ProfessionalSkill " +
                "WHERE numProfessionalSkill = ?";

        try {
            prStat = connect.prepareStatement(query);
            prStat.setInt(1, idToSearch);
            rs = prStat.executeQuery();

            if (rs.next()) {
                professionalSkillFind = new ProfessionalSkill(
                        rs.getInt("numProfessionalSkill"),
                        rs.getString("designation")
                );
            }
        } finally {
            closeStatementAndResultSet(prStat, rs);
        }
        return professionalSkillFind;
    }

    /**
     * Searches all the professional skills to the interpreter
     *
     * @param numInterpreter the id of the interpreter we are looking for professional skills
     * @return a list containing all the Professional skills to the interpreter
     * @throws SQLException In case of any SQL problems encountered with this method.
     */
    public List<ProfessionalSkill> findByInterpreter(int numInterpreter) throws SQLException {
        List<ProfessionalSkill> professionalSkills = new ArrayList<>();
        ProfessionalSkill professionalSkill = null;
        PreparedStatement prStat = null;
        ResultSet resultSet = null;
        String query = "SELECT * FROM ProfessionalSkill ps " +
                "JOIN ProfessionalSkillInterpreter psi ON ps.numProfessionalSkill = psi.numProfessionalSkill " +
                "WHERE psi.numInterpreter = ?";
        try {
            prStat = connect.prepareStatement(query);
            prStat.setInt(1, numInterpreter);
            resultSet = prStat.executeQuery();
            while (resultSet.next()) {
                professionalSkill = new ProfessionalSkill(
                        resultSet.getInt("NumProfessionalSkill"),
                        resultSet.getString("Designation"));
                professionalSkills.add(professionalSkill);
            }
        } finally {
            closeStatementAndResultSet(prStat, resultSet);
        }
        return professionalSkills;
    }

    /**
     * Creates a list containing all the ProfessionalSkills in the table.
     *
     * @return a list containing all the ProfessionalSkills, or an empty list if the table is empty.
     * @throws SQLException In case of any SQL problems encountered with this method.
     */
    @Override
    public List<ProfessionalSkill> findAll() throws SQLException {
        List<ProfessionalSkill> listProfessionalSkills = new ArrayList<>();
        PreparedStatement prStat = null;
        ResultSet rs = null;

        String query = "SELECT numProfessionalSkill, designation " +
                "FROM ProfessionalSkill";

        try {
            prStat = connect.prepareStatement(query);
            rs = prStat.executeQuery();

            while (rs.next()) {
                ProfessionalSkill professionalSkillTrouve = new ProfessionalSkill(
                        rs.getInt("numProfessionalSkill"),
                        rs.getString("designation")
                );
                listProfessionalSkills.add(professionalSkillTrouve);
            }
        } finally {
            closeStatementAndResultSet(prStat, rs);
        }
        return listProfessionalSkills;
    }

    /**
     * Adds the ProfessionalSkill passed as a parameter to the table.
     * The numInterpreter is auto-generated by Oracle and retrieved via RETURNING INTO.
     * It must therefore not be included in the INSERT statement.
     * Precondition: the ProfessionalSkill passed as a parameter cannot be null.
     *
     * @param objectToInsertInDB the ProfessionalSkill to be inserted into the table.
     * @return true if the ProfessionalSkill was successfully inserted, false otherwise.
     * @throws SQLException In case of any SQL problems encountered with this method.
     */
    @Override
    public boolean create(ProfessionalSkill objectToInsertInDB) throws SQLException {
        boolean isInserted = false;
        OraclePreparedStatement prStat = null;
        ResultSet generateID = null;

        String query = "INSERT INTO ProfessionalSkill (designation) " +
                "VALUES (?) " +
                "RETURNING numProfessionalSkill INTO ?";

        try {
            prStat = (OraclePreparedStatement) connect.prepareStatement(query);
            prStat.setString(1, objectToInsertInDB.getDesignation());
            prStat.registerReturnParameter(2, OracleTypes.INTEGER);

            int nbLinesInsert = prStat.executeUpdate();
            if (nbLinesInsert > 0) {
                generateID = prStat.getReturnResultSet();
                if (!generateID.next()) {
                    throw new SQLException("[DAOProfessionalSkill] Impossible de récupérer le numProfessionalSkill généré.");
                }
                int numProfessionalSkillGenerated = generateID.getInt(1);
                objectToInsertInDB.setNumProfessionalSkill(numProfessionalSkillGenerated);

                isInserted = true;
            }
        } finally {
            closeStatementAndResultSet(prStat, generateID);
        }
        return isInserted;
    }

    /**
     * Updates the designation field of the ProfessionalSkill in the table
     * that corresponds to the numProfessionalSkill of the ProfessionalSkill passed as a parameter.
     * Precondition: the ProfessionalSkill passed as a parameter cannot be null.
     *
     * @param objectToUpdateInDB the ProfessionalSkill containing the numProfessionalSkill and the designation to update.
     * @return true if the ProfessionalSkill was successfully updated, false otherwise.
     * @throws SQLException In case of any SQL problems encountered with this method.
     */
    @Override
    public boolean update(ProfessionalSkill objectToUpdateInDB) throws SQLException {
        boolean isUpdated = false;
        PreparedStatement prStat = null;

        String query = "UPDATE ProfessionalSkill " +
                "SET designation = ? " +
                "WHERE numProfessionalSkill = ?";

        try {
            prStat = connect.prepareStatement(query);
            prStat.setString(1, objectToUpdateInDB.getDesignation());
            prStat.setInt(2, objectToUpdateInDB.getNumProfessionalSkill());

            int nbLinesUpdate = prStat.executeUpdate();
            if (nbLinesUpdate > 0) {
                isUpdated = true;
            }
        } finally {
            closeStatement(prStat);
        }

        return isUpdated;
    }

    /**
     * Deletes the ProfessionalSkill whose numProfessionalSkill matches
     * the numProfessionalSkill of the ProfessionalSkill passed as a parameter.
     * Precondition: the ProfessionalSkill passed as a parameter cannot be null.
     *
     * @param objectToDeleteFormDB the ProfessionalSkill to be deleted from the table.
     * @return true if the ProfessionalSkill was successfully deleted, false otherwise.
     * @throws SQLException In case of any SQL problems encountered with this method.
     */
    @Override
    public boolean delete(ProfessionalSkill objectToDeleteFormDB) throws SQLException {
        boolean isDeleted = false;
        PreparedStatement prStat = null;

        String query = "DELETE FROM ProfessionalSkill " +
                "WHERE numProfessionalSkill = ?";

        try {
            prStat = connect.prepareStatement(query);
            prStat.setInt(1, objectToDeleteFormDB.getNumProfessionalSkill());

            int nbLinesDelete = prStat.executeUpdate();
            if (nbLinesDelete > 0) {
                isDeleted = true;
            }
        } finally {
            closeStatement(prStat);
        }
        return isDeleted;
    }
}
