
Create table Collaborateur (
                               ID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                               nom varchar2(255) not null,
                               prenom varchar2(255) not null),
                                UNIQUE (col1, col2);

Create table Tache (
                       ID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                       description varchar2(255) not null,
                       echeance date not null,
                       StatusGlobal VARCHAR2(255) not null,
                       StatusTiming VARCHAR2(255) not null,
                       FKCollaborateur INTEGER not null,
                       CONSTRAINT FKCollaborateurTache FOREIGN KEY(FKCollaborateur) REFERENCES Collaborateur (ID),
                       FKTravailleur INTEGER,
                       CONSTRAINT FKTravailleurTache FOREIGN KEY(FKTravailleur) REFERENCES Collaborateur (ID));

Create table PeriodeTravail (
                                ID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                nbrMinutes INTEGER not null,
                                FKTache INTEGER not null,
                                CONSTRAINT FKTachePeriodeTravail FOREIGN KEY(FKTache) REFERENCES Tache (ID),
                                FKCollaborateur INTEGER not null,
                                CONSTRAINT FKCollaborateurPeriodeTravail FOREIGN KEY(FKCollaborateur) REFERENCES Collaborateur (ID),
                                dateDebut DATE not null);
